いいね機能を実装したのでご確認お願いします。
koudaikumazaki/team-development pull request #13
Opened 2021-03-29 12:52 UTC by House-lovers7

完了定義は以下です。
 
 ・1ユーザーあたり、1投稿に対して1回のみいいねが押せるようになっている 
・いいねが押されている状態でもう一度いいねを押すと、いいねが取り消される
・未ログイン時にはいいねボタンを押せないようになっている
・いいねをカウントできている

https://qiita.com/haruuu132/items/c5748c24fa96fbc55e47
上記記事に従い、binding.pryもついでにインストールしています。

2021-03-29 23:55 UTC, koudaikumazaki commented on app/assets/stylesheets/likes.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
こいつは消しておきましょう！

2021-03-30 00:00 UTC, koudaikumazaki commented on test/controllers/likes_controller_test.rb
> +end
これも不要なので消しておきましょう！

2021-03-30 00:05 UTC, koudaikumazaki reviewed
ほぼOKです！
一部不要なファイルだけ削除していただければ、壮さんにレビューお願いして大丈夫です！

2021-03-30 00:24 UTC, House-lovers7 commented on app/assets/stylesheets/likes.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
消しました。

2021-03-30 00:24 UTC, House-lovers7 commented on test/controllers/likes_controller_test.rb
> +end
消しました。

2021-03-30 04:10 UTC, s-ryota0810 reviewed
レビュー完了しました。
ご確認をお願いします！

2021-03-30 04:10 UTC, s-ryota0810 commented on app/controllers/likes_controller.rb
> +      end
ここからインデントがズレているので調整をお願いします！

2021-03-30 16:33 UTC, sew-sou19 requested changes
レビュー完了しました。
ご確認お願いしますー！

2021-03-30 16:33 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +      end
ryotaさんのご指摘通りインデントは修正しましょうー！

2021-03-30 16:33 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    @like =  Like.new
Like.newは不要だと思いますー！

2021-03-30 16:33 UTC, sew-sou19 commented on app/views/posts/index.html.erb
> +                      <% if current_user.nil? %>
未ログイン時にエラー起きないですかね？
起きなければ大丈夫です！

2021-03-31 13:05 UTC, House-lovers7 commented on app/controllers/likes_controller.rb
> +      end
訂正しました!

2021-03-31 13:06 UTC, House-lovers7 commented on app/controllers/posts_controller.rb
> +    @like =  Like.new
消しました!

2021-03-31 13:07 UTC, House-lovers7 commented on app/views/posts/index.html.erb
> +                      <% if current_user.nil? %>
起きないので、このまま行きます。

2021-03-31 13:14 UTC, House-lovers7 commented on app/views/posts/index.html.erb
> +                      <% if current_user.nil? %>
問題ないので、このまま行きます。

2021-04-02 11:32 UTC, koudaikumazaki reviewed
コンフリクトの修正を確認しました！
お忙しい中ご対応いただき、誠にありがとうございます！

2021-04-02 11:35 UTC, sew-sou19 approved these changes
内容は問題ないのでApproveしておきました！
コメントした部分は念のためご確認ください！

2021-04-02 11:35 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    @posts = Post.all
スペースかタブが入ってしまっているようなので元に戻しましょう！
基本的に自分が修正した箇所以外は差分が出ないようにしましょうー（意図しない変更によってバグが発生することがあるので）

プルリクのFIles Changedタブを見ると差分が一覧で確認できるので、レビュー依頼をする前に必ず自分でチェックしてください！

2021-04-02 11:51 UTC, merged