Add board function
koudaikumazaki/team-development pull request #7
Opened 2021-03-24 11:42 UTC by koudaikumazaki

掲示板一覧表示機能・投稿詳細機能・投稿機能を終了いたしました！
お忙しい中誠に恐れ入りますが、ご確認の程宜しくお願い致します。

2021-03-24 12:48 UTC, sew-sou19 commented
コミットはできるだけ細かく分けましょう！
1コミット一意が理想です！

2021-03-24 12:57 UTC, sew-sou19 requested changes
レビュー完了しました！
確認と修正をお願いしますー！

2021-03-24 12:57 UTC, sew-sou19 commented on Gemfile
> +  # 掲示板の一覧画面のN+1問題を解決するためにインストールしました。
コメントは極力使わないようにしましょう！
基本的に共有事項はSlackなどで行ってください。

2021-03-24 12:57 UTC, sew-sou19 commented on app/assets/stylesheets/posts.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
不要なscssファイルは混乱を招くので削除しましょうー！

2021-03-24 12:57 UTC, sew-sou19 commented on app/assets/stylesheets/templates/_posts.scss
> +            // デフォルトのcssを改変した。
こちらもコメントは不要です！
どうしてもGitHub上に残したければコミットメッセージなどを使いましょう！

2021-03-24 12:57 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +  end
今回実装しない機能のアクションは記述しないようにしましょう！
「YAGNI原則」を調べてみてください。

2021-03-24 12:57 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +  end
こちらも今回の実装では不要な記述かと思いますので、極力YAGNI原則に則りましょうー！

2021-03-24 12:57 UTC, sew-sou19 commented on app/views/posts/index.html.erb
> +      <%# each文で投稿一覧を表示すること %>
不要なコメントは削除しましょう！

2021-03-24 12:57 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    @post.user_id = current_user.id
hidden_fieldでuser_idをPostしてるので、この記述は不要だと思います！

2021-03-24 12:57 UTC, sew-sou19 commented on app/views/templates/_header.html.erb
>        <%# ルートパスへのリンクを設置 %>
不要なコメントなので削除しましょうー！

2021-03-24 12:57 UTC, sew-sou19 commented on config/boot.rb
> +
この変更は何か理由がありますか？
変更に理由がないものはcommitしないようにしましょうー！

2021-03-24 12:57 UTC, sew-sou19 commented on config/environments/development.rb
> +  # 以下、N+1問題解決のためにgemを導入しました。
こちらもコメントは不要です！

2021-03-24 12:57 UTC, sew-sou19 commented on config/routes.rb
> +  root 'posts#index'
routes.rbは上から読み込まれるので、rootパスは最上部で定義しましょう！

2021-03-24 12:57 UTC, sew-sou19 commented on config/routes.rb
> +  get 'posts/show'
resourcesがあるのでこの記述は不要です！

2021-03-24 12:57 UTC, sew-sou19 commented on config/routes.rb
> +    post 'users/second_guest_sign_in', to: 'users/sessions#guest_user'
これも今回の実装では不要な記述だと思いますー！

2021-03-24 13:05 UTC, koudaikumazaki commented on Gemfile
> +  # 掲示板の一覧画面のN+1問題を解決するためにインストールしました。
コードに書いた方が親切だと思ってました！
次回以降はslackで共有するようにします！！

2021-03-24 13:05 UTC, koudaikumazaki commented on app/assets/stylesheets/posts.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
自動生成したままにしてました。削除しておきました。

2021-03-24 13:05 UTC, koudaikumazaki commented on app/assets/stylesheets/templates/_posts.scss
> +            // デフォルトのcssを改変した。
こちらも削除しました！

2021-03-24 13:08 UTC, koudaikumazaki commented on app/controllers/posts_controller.rb
> +  end
実際に必要になった際にのみ機能を追加するということですね！
削除しておきました。

2021-03-24 13:09 UTC, koudaikumazaki commented on app/controllers/posts_controller.rb
> +  end
こちらもYAGNI原則に則り修正しました。

2021-03-24 13:10 UTC, koudaikumazaki commented on app/views/posts/index.html.erb
> +      <%# each文で投稿一覧を表示すること %>
削除しました！

2021-03-24 13:12 UTC, koudaikumazaki commented on app/views/templates/_header.html.erb
>        <%# ルートパスへのリンクを設置 %>
削除しました！

2021-03-24 13:12 UTC, koudaikumazaki commented on config/routes.rb
> +    post 'users/second_guest_sign_in', to: 'users/sessions#guest_user'
こちらも削除しました！

2021-03-24 13:13 UTC, koudaikumazaki commented on config/routes.rb
> +  get 'posts/show'
こちらも削除しました！

2021-03-24 13:14 UTC, koudaikumazaki commented on config/routes.rb
> +  root 'posts#index'
最上部に定義しました！

2021-03-24 13:39 UTC, koudaikumazaki commented on config/environments/development.rb
> +  # 以下、N+1問題解決のためにgemを導入しました。
コメント削除しました！

2021-03-24 13:52 UTC, koudaikumazaki commented on app/controllers/posts_controller.rb
> +    @post.user_id = current_user.id
こちらですが、@post.user_id = current_user.idを削除するとバリデーションエラーになってしまいました、、、
ですので、hidden_fieldの方を削除して対応しました！

2021-03-24 14:09 UTC, koudaikumazaki commented on config/boot.rb
> +
こちらbulletの導入の際に試したことなのですが、このコードは必要ないものでした。
そのため、削除しました！

2021-03-24 14:30 UTC, koudaikumazaki commented on Gemfile
>    gem 'bullet'
コメントは避けるようにご指摘いただいたので、削除しました。

2021-03-24 14:30 UTC, koudaikumazaki commented on app/assets/stylesheets/templates/_posts.scss
>              height: 218px;
こちらもコメントを削除しております。

2021-03-24 14:31 UTC, koudaikumazaki commented on app/controllers/posts_controller.rb
YAGNI原則に則って未実装のアクションを削除しました。

2021-03-24 14:32 UTC, koudaikumazaki commented on app/controllers/posts_controller.rb
>  end
こちらもYAGNI原則にしたがって削除しております。

2021-03-24 14:33 UTC, koudaikumazaki commented on app/views/posts/index.html.erb
>        <% if @posts == nil %>
不要なコメントを削除しました。

2021-03-24 14:35 UTC, koudaikumazaki commented on app/views/posts/new.html.erb
>            <div class="form_area__action">
前のコードレビューで、posts_controller.rbのcreateアクション内にある@post.user_id = current_user.idを削除しても問題ないというご指摘をいただき、削除したのですがバリデーションエラーが発生してしまいました。
そのため、posts_controller.rbはそのままにしてこちらを削除して対応しました。

2021-03-24 14:36 UTC, koudaikumazaki commented on app/views/templates/_header.html.erb
>      <% if user_signed_in? %>
不要なコメントを削除しています。

2021-03-24 14:36 UTC, koudaikumazaki commented on config/routes.rb
>    end
こちら、削除しております。

2021-03-24 14:36 UTC, koudaikumazaki commented on config/routes.rb
>  end
最上部に移動しました。

2021-03-24 14:37 UTC, koudaikumazaki commented on config/routes.rb
>      registrations: 'users/registrations',
resourceで定義していたため、こちらは削除しました。

2021-03-25 01:16 UTC, sew-sou19 commented on Gemfile
> +  # 掲示板の一覧画面のN+1問題を解決するためにインストールしました。
現場では極力コードにコメントは書かないことが推奨されてます。
例えば仕様を変えた時に、コードとコメントの両方を修正しないといけないので、二重管理になる＆どちらか修正漏れたら第三者に混乱を与えるなどが理由です！

2021-03-25 01:21 UTC, sew-sou19 approved these changes
LGTMですー！
※コミットはまとめてではなく細かく分けてコミットするようにしましょう！
1コミット一意が理想です！

2021-03-25 01:21 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    @post.user_id = current_user.id
おそらくテンプレート側のvalueの定義の仕方っぽかったですね〜
これでも大丈夫です！

2021-03-25 01:21 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    params.require(:post).permit(:content, :created_at, :user_id)
これでも大丈夫ですが、受け取らない値の:user_idは削除しておきましょうー！

2021-03-25 01:28 UTC, merged